//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Babelfisk.Warehouse.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Animal))]
    [KnownType(typeof(Sample))]
    public partial class SpeciesList: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int speciesListId
        {
            get { return _speciesListId; }
            set
            {
                if (_speciesListId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'speciesListId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _speciesListId = value;
                    OnPropertyChanged("speciesListId");
                }
            }
        }
        private int _speciesListId;
    
        [DataMember]
        public int sampleId
        {
            get { return _sampleId; }
            set
            {
                if (_sampleId != value)
                {
                    ChangeTracker.RecordOriginalValue("sampleId", _sampleId);
                    if (!IsDeserializing)
                    {
                        if (Sample != null && Sample.sampleId != value)
                        {
                            Sample = null;
                        }
                    }
                    _sampleId = value;
                    OnPropertyChanged("sampleId");
                }
            }
        }
        private int _sampleId;
    
        [DataMember]
        public int year
        {
            get { return _year; }
            set
            {
                if (_year != value)
                {
                    _year = value;
                    OnPropertyChanged("year");
                }
            }
        }
        private int _year;
    
        [DataMember]
        public string cruise
        {
            get { return _cruise; }
            set
            {
                if (_cruise != value)
                {
                    _cruise = value;
                    OnPropertyChanged("cruise");
                }
            }
        }
        private string _cruise;
    
        [DataMember]
        public string trip
        {
            get { return _trip; }
            set
            {
                if (_trip != value)
                {
                    _trip = value;
                    OnPropertyChanged("trip");
                }
            }
        }
        private string _trip;
    
        [DataMember]
        public string tripType
        {
            get { return _tripType; }
            set
            {
                if (_tripType != value)
                {
                    _tripType = value;
                    OnPropertyChanged("tripType");
                }
            }
        }
        private string _tripType;
    
        [DataMember]
        public string station
        {
            get { return _station; }
            set
            {
                if (_station != value)
                {
                    _station = value;
                    OnPropertyChanged("station");
                }
            }
        }
        private string _station;
    
        [DataMember]
        public System.DateTime dateGearStart
        {
            get { return _dateGearStart; }
            set
            {
                if (_dateGearStart != value)
                {
                    _dateGearStart = value;
                    OnPropertyChanged("dateGearStart");
                }
            }
        }
        private System.DateTime _dateGearStart;
    
        [DataMember]
        public Nullable<int> quarterGearStart
        {
            get { return _quarterGearStart; }
            set
            {
                if (_quarterGearStart != value)
                {
                    _quarterGearStart = value;
                    OnPropertyChanged("quarterGearStart");
                }
            }
        }
        private Nullable<int> _quarterGearStart;
    
        [DataMember]
        public string dfuArea
        {
            get { return _dfuArea; }
            set
            {
                if (_dfuArea != value)
                {
                    _dfuArea = value;
                    OnPropertyChanged("dfuArea");
                }
            }
        }
        private string _dfuArea;
    
        [DataMember]
        public string statisticalRectangle
        {
            get { return _statisticalRectangle; }
            set
            {
                if (_statisticalRectangle != value)
                {
                    _statisticalRectangle = value;
                    OnPropertyChanged("statisticalRectangle");
                }
            }
        }
        private string _statisticalRectangle;
    
        [DataMember]
        public string gearQuality
        {
            get { return _gearQuality; }
            set
            {
                if (_gearQuality != value)
                {
                    _gearQuality = value;
                    OnPropertyChanged("gearQuality");
                }
            }
        }
        private string _gearQuality;
    
        [DataMember]
        public string gearType
        {
            get { return _gearType; }
            set
            {
                if (_gearType != value)
                {
                    _gearType = value;
                    OnPropertyChanged("gearType");
                }
            }
        }
        private string _gearType;
    
        [DataMember]
        public Nullable<decimal> meshSize
        {
            get { return _meshSize; }
            set
            {
                if (_meshSize != value)
                {
                    _meshSize = value;
                    OnPropertyChanged("meshSize");
                }
            }
        }
        private Nullable<decimal> _meshSize;
    
        [DataMember]
        public string speciesCode
        {
            get { return _speciesCode; }
            set
            {
                if (_speciesCode != value)
                {
                    _speciesCode = value;
                    OnPropertyChanged("speciesCode");
                }
            }
        }
        private string _speciesCode;
    
        [DataMember]
        public string stock
        {
            get { return _stock; }
            set
            {
                if (_stock != value)
                {
                    _stock = value;
                    OnPropertyChanged("stock");
                }
            }
        }
        private string _stock;
    
        [DataMember]
        public string landingCategory
        {
            get { return _landingCategory; }
            set
            {
                if (_landingCategory != value)
                {
                    _landingCategory = value;
                    OnPropertyChanged("landingCategory");
                }
            }
        }
        private string _landingCategory;
    
        [DataMember]
        public string dfuBase_Category
        {
            get { return _dfuBase_Category; }
            set
            {
                if (_dfuBase_Category != value)
                {
                    _dfuBase_Category = value;
                    OnPropertyChanged("dfuBase_Category");
                }
            }
        }
        private string _dfuBase_Category;
    
        [DataMember]
        public Nullable<int> sizeSortingEU
        {
            get { return _sizeSortingEU; }
            set
            {
                if (_sizeSortingEU != value)
                {
                    _sizeSortingEU = value;
                    OnPropertyChanged("sizeSortingEU");
                }
            }
        }
        private Nullable<int> _sizeSortingEU;
    
        [DataMember]
        public string sizeSortingDFU
        {
            get { return _sizeSortingDFU; }
            set
            {
                if (_sizeSortingDFU != value)
                {
                    _sizeSortingDFU = value;
                    OnPropertyChanged("sizeSortingDFU");
                }
            }
        }
        private string _sizeSortingDFU;
    
        [DataMember]
        public string sexCode
        {
            get { return _sexCode; }
            set
            {
                if (_sexCode != value)
                {
                    _sexCode = value;
                    OnPropertyChanged("sexCode");
                }
            }
        }
        private string _sexCode;
    
        [DataMember]
        public string ovigorous
        {
            get { return _ovigorous; }
            set
            {
                if (_ovigorous != value)
                {
                    _ovigorous = value;
                    OnPropertyChanged("ovigorous");
                }
            }
        }
        private string _ovigorous;
    
        [DataMember]
        public string cuticulaHardness
        {
            get { return _cuticulaHardness; }
            set
            {
                if (_cuticulaHardness != value)
                {
                    _cuticulaHardness = value;
                    OnPropertyChanged("cuticulaHardness");
                }
            }
        }
        private string _cuticulaHardness;
    
        [DataMember]
        public string treatment
        {
            get { return _treatment; }
            set
            {
                if (_treatment != value)
                {
                    _treatment = value;
                    OnPropertyChanged("treatment");
                }
            }
        }
        private string _treatment;
    
        [DataMember]
        public Nullable<decimal> weightStep0
        {
            get { return _weightStep0; }
            set
            {
                if (_weightStep0 != value)
                {
                    _weightStep0 = value;
                    OnPropertyChanged("weightStep0");
                }
            }
        }
        private Nullable<decimal> _weightStep0;
    
        [DataMember]
        public Nullable<decimal> weightStep1
        {
            get { return _weightStep1; }
            set
            {
                if (_weightStep1 != value)
                {
                    _weightStep1 = value;
                    OnPropertyChanged("weightStep1");
                }
            }
        }
        private Nullable<decimal> _weightStep1;
    
        [DataMember]
        public Nullable<decimal> weightStep2
        {
            get { return _weightStep2; }
            set
            {
                if (_weightStep2 != value)
                {
                    _weightStep2 = value;
                    OnPropertyChanged("weightStep2");
                }
            }
        }
        private Nullable<decimal> _weightStep2;
    
        [DataMember]
        public Nullable<decimal> weightStep3
        {
            get { return _weightStep3; }
            set
            {
                if (_weightStep3 != value)
                {
                    _weightStep3 = value;
                    OnPropertyChanged("weightStep3");
                }
            }
        }
        private Nullable<decimal> _weightStep3;
    
        [DataMember]
        public Nullable<decimal> landingWeightStep0
        {
            get { return _landingWeightStep0; }
            set
            {
                if (_landingWeightStep0 != value)
                {
                    _landingWeightStep0 = value;
                    OnPropertyChanged("landingWeightStep0");
                }
            }
        }
        private Nullable<decimal> _landingWeightStep0;
    
        [DataMember]
        public Nullable<decimal> landingWeightStep1
        {
            get { return _landingWeightStep1; }
            set
            {
                if (_landingWeightStep1 != value)
                {
                    _landingWeightStep1 = value;
                    OnPropertyChanged("landingWeightStep1");
                }
            }
        }
        private Nullable<decimal> _landingWeightStep1;
    
        [DataMember]
        public Nullable<decimal> treatmentFactor
        {
            get { return _treatmentFactor; }
            set
            {
                if (_treatmentFactor != value)
                {
                    _treatmentFactor = value;
                    OnPropertyChanged("treatmentFactor");
                }
            }
        }
        private Nullable<decimal> _treatmentFactor;
    
        [DataMember]
        public Nullable<decimal> raisingFactor
        {
            get { return _raisingFactor; }
            set
            {
                if (_raisingFactor != value)
                {
                    _raisingFactor = value;
                    OnPropertyChanged("raisingFactor");
                }
            }
        }
        private Nullable<decimal> _raisingFactor;
    
        [DataMember]
        public string wemSpeciesList
        {
            get { return _wemSpeciesList; }
            set
            {
                if (_wemSpeciesList != value)
                {
                    _wemSpeciesList = value;
                    OnPropertyChanged("wemSpeciesList");
                }
            }
        }
        private string _wemSpeciesList;
    
        [DataMember]
        public Nullable<decimal> weightNonRep
        {
            get { return _weightNonRep; }
            set
            {
                if (_weightNonRep != value)
                {
                    _weightNonRep = value;
                    OnPropertyChanged("weightNonRep");
                }
            }
        }
        private Nullable<decimal> _weightNonRep;
    
        [DataMember]
        public Nullable<decimal> bmsNonRep
        {
            get { return _bmsNonRep; }
            set
            {
                if (_bmsNonRep != value)
                {
                    _bmsNonRep = value;
                    OnPropertyChanged("bmsNonRep");
                }
            }
        }
        private Nullable<decimal> _bmsNonRep;
    
        [DataMember]
        public Nullable<int> number
        {
            get { return _number; }
            set
            {
                if (_number != value)
                {
                    _number = value;
                    OnPropertyChanged("number");
                }
            }
        }
        private Nullable<int> _number;
    
        [DataMember]
        public Nullable<decimal> totalWeight
        {
            get { return _totalWeight; }
            set
            {
                if (_totalWeight != value)
                {
                    _totalWeight = value;
                    OnPropertyChanged("totalWeight");
                }
            }
        }
        private Nullable<decimal> _totalWeight;
    
        [DataMember]
        public string wemTotalWeight
        {
            get { return _wemTotalWeight; }
            set
            {
                if (_wemTotalWeight != value)
                {
                    _wemTotalWeight = value;
                    OnPropertyChanged("wemTotalWeight");
                }
            }
        }
        private string _wemTotalWeight;
    
        [DataMember]
        public string remark
        {
            get { return _remark; }
            set
            {
                if (_remark != value)
                {
                    _remark = value;
                    OnPropertyChanged("remark");
                }
            }
        }
        private string _remark;
    
        [DataMember]
        public string applicationCode
        {
            get { return _applicationCode; }
            set
            {
                if (_applicationCode != value)
                {
                    _applicationCode = value;
                    OnPropertyChanged("applicationCode");
                }
            }
        }
        private string _applicationCode;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Animal> Animals
        {
            get
            {
                if (_animals == null)
                {
                    _animals = new TrackableCollection<Animal>();
                    _animals.CollectionChanged += FixupAnimals;
                }
                return _animals;
            }
            set
            {
                if (!ReferenceEquals(_animals, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_animals != null)
                    {
                        _animals.CollectionChanged -= FixupAnimals;
                    }
                    _animals = value;
                    if (_animals != null)
                    {
                        _animals.CollectionChanged += FixupAnimals;
                    }
                    OnNavigationPropertyChanged("Animals");
                }
            }
        }
        private TrackableCollection<Animal> _animals;
    
        [DataMember]
        public Sample Sample
        {
            get { return _sample; }
            set
            {
                if (!ReferenceEquals(_sample, value))
                {
                    var previousValue = _sample;
                    _sample = value;
                    FixupSample(previousValue);
                    OnNavigationPropertyChanged("Sample");
                }
            }
        }
        private Sample _sample;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Animals.Clear();
            Sample = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupSample(Sample previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.SpeciesLists.Contains(this))
            {
                previousValue.SpeciesLists.Remove(this);
            }
    
            if (Sample != null)
            {
                if (!Sample.SpeciesLists.Contains(this))
                {
                    Sample.SpeciesLists.Add(this);
                }
    
                sampleId = Sample.sampleId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Sample")
                    && (ChangeTracker.OriginalValues["Sample"] == Sample))
                {
                    ChangeTracker.OriginalValues.Remove("Sample");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Sample", previousValue);
                }
                if (Sample != null && !Sample.ChangeTracker.ChangeTrackingEnabled)
                {
                    Sample.StartTracking();
                }
            }
        }
    
        private void FixupAnimals(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Animal item in e.NewItems)
                {
                    item.SpeciesList = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Animals", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Animal item in e.OldItems)
                {
                    if (ReferenceEquals(item.SpeciesList, this))
                    {
                        item.SpeciesList = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Animals", item);
                    }
                }
            }
        }

        #endregion

    }
}
