//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Babelfisk.BusinessLogic.SIS.Model
{
    [DataContract(IsReference = true)]
    public partial class Instruments
    {
        #region Primitive Properties
        [DataMember]
        public virtual short machineNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual short instrNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string instrName
        {
            get;
            set;
        }
        [DataMember]
        public virtual short onOff
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> timeUpdate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<short> maxTime
        {
            get;
            set;
        }

        #endregion
    }
}
