//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Babelfisk.BusinessLogic.SIS.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(L_ParamListe))]
    [KnownType(typeof(TrawlLog))]
    public partial class TrawlData
    {
        #region Primitive Properties
        [DataMember]
        public virtual int sampleID
        {
            get { return _sampleID; }
            set
            {
                if (_sampleID != value)
                {
                    if (TrawlLog != null && TrawlLog.sampleID != value)
                    {
                        TrawlLog = null;
                    }
                    _sampleID = value;
                }
            }
        }
        private int _sampleID;
        [DataMember]
        public virtual string paramCode
        {
            get { return _paramCode; }
            set
            {
                if (_paramCode != value)
                {
                    if (L_ParamListe != null && L_ParamListe.paramCode != value)
                    {
                        L_ParamListe = null;
                    }
                    _paramCode = value;
                }
            }
        }
        private string _paramCode;
        [DataMember]
        public virtual short sensorNumber
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<float> result
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<short> quality
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual L_ParamListe L_ParamListe
        {
            get { return _l_ParamListe; }
            set
            {
                if (!ReferenceEquals(_l_ParamListe, value))
                {
                    var previousValue = _l_ParamListe;
                    _l_ParamListe = value;
                    FixupL_ParamListe(previousValue);
                }
            }
        }
        private L_ParamListe _l_ParamListe;
        
    
        [DataMember]
        public virtual TrawlLog TrawlLog
        {
            get { return _trawlLog; }
            set
            {
                if (!ReferenceEquals(_trawlLog, value))
                {
                    var previousValue = _trawlLog;
                    _trawlLog = value;
                    FixupTrawlLog(previousValue);
                }
            }
        }
        private TrawlLog _trawlLog;

        #endregion
        #region Association Fixup
    
        private void FixupL_ParamListe(L_ParamListe previousValue)
        {
            if (previousValue != null && previousValue.TrawlData.Contains(this))
            {
                previousValue.TrawlData.Remove(this);
            }
    
            if (L_ParamListe != null)
            {
                if (!L_ParamListe.TrawlData.Contains(this))
                {
                    L_ParamListe.TrawlData.Add(this);
                }
                if (paramCode != L_ParamListe.paramCode)
                {
                    paramCode = L_ParamListe.paramCode;
                }
            }
        }
    
        private void FixupTrawlLog(TrawlLog previousValue)
        {
            if (previousValue != null && previousValue.TrawlData.Contains(this))
            {
                previousValue.TrawlData.Remove(this);
            }
    
            if (TrawlLog != null)
            {
                if (!TrawlLog.TrawlData.Contains(this))
                {
                    TrawlLog.TrawlData.Add(this);
                }
                if (sampleID != TrawlLog.sampleID)
                {
                    sampleID = TrawlLog.sampleID;
                }
            }
        }

        #endregion
    }
}
