//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Babelfisk.Entities.Sprattus
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(R_StockSpeciesArea))]
    [KnownType(typeof(R_SDReader))]
    public partial class L_Stock: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int L_stockId
        {
            get { return _l_stockId; }
            set
            {
                if (_l_stockId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'L_stockId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _l_stockId = value;
                    OnPropertyChanged("L_stockId");
                }
            }
        }
        private int _l_stockId;
    
        [DataMember]
        public string stockCode
        {
            get { return _stockCode; }
            set
            {
                if (_stockCode != value)
                {
                    _stockCode = value;
                    OnPropertyChanged("stockCode");
                }
            }
        }
        private string _stockCode;
    
        [DataMember]
        public string description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("description");
                }
            }
        }
        private string _description;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<R_StockSpeciesArea> R_StockSpeciesArea
        {
            get
            {
                if (_r_StockSpeciesArea == null)
                {
                    _r_StockSpeciesArea = new TrackableCollection<R_StockSpeciesArea>();
                    _r_StockSpeciesArea.CollectionChanged += FixupR_StockSpeciesArea;
                }
                return _r_StockSpeciesArea;
            }
            set
            {
                if (!ReferenceEquals(_r_StockSpeciesArea, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_r_StockSpeciesArea != null)
                    {
                        _r_StockSpeciesArea.CollectionChanged -= FixupR_StockSpeciesArea;
                    }
                    _r_StockSpeciesArea = value;
                    if (_r_StockSpeciesArea != null)
                    {
                        _r_StockSpeciesArea.CollectionChanged += FixupR_StockSpeciesArea;
                    }
                    OnNavigationPropertyChanged("R_StockSpeciesArea");
                }
            }
        }
        private TrackableCollection<R_StockSpeciesArea> _r_StockSpeciesArea;
    
        [DataMember]
        public TrackableCollection<R_SDReader> R_SDReader
        {
            get
            {
                if (_r_SDReader == null)
                {
                    _r_SDReader = new TrackableCollection<R_SDReader>();
                    _r_SDReader.CollectionChanged += FixupR_SDReader;
                }
                return _r_SDReader;
            }
            set
            {
                if (!ReferenceEquals(_r_SDReader, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_r_SDReader != null)
                    {
                        _r_SDReader.CollectionChanged -= FixupR_SDReader;
                    }
                    _r_SDReader = value;
                    if (_r_SDReader != null)
                    {
                        _r_SDReader.CollectionChanged += FixupR_SDReader;
                    }
                    OnNavigationPropertyChanged("R_SDReader");
                }
            }
        }
        private TrackableCollection<R_SDReader> _r_SDReader;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            R_StockSpeciesArea.Clear();
            R_SDReader.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupR_StockSpeciesArea(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (R_StockSpeciesArea item in e.NewItems)
                {
                    item.L_Stock = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("R_StockSpeciesArea", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (R_StockSpeciesArea item in e.OldItems)
                {
                    if (ReferenceEquals(item.L_Stock, this))
                    {
                        item.L_Stock = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("R_StockSpeciesArea", item);
                    }
                }
            }
        }
    
        private void FixupR_SDReader(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (R_SDReader item in e.NewItems)
                {
                    item.L_Stock = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("R_SDReader", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (R_SDReader item in e.OldItems)
                {
                    if (ReferenceEquals(item.L_Stock, this))
                    {
                        item.L_Stock = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("R_SDReader", item);
                    }
                }
            }
        }

        #endregion

    }
}
