//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Babelfisk.Entities.Sprattus
{
    [DataContract(IsReference = true)]
    public partial class QueryTypes: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int QueryTypeID
        {
            get { return _queryTypeID; }
            set
            {
                if (_queryTypeID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'QueryTypeID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _queryTypeID = value;
                    OnPropertyChanged("QueryTypeID");
                }
            }
        }
        private int _queryTypeID;
    
        [DataMember]
        public string tblAlias
        {
            get { return _tblAlias; }
            set
            {
                if (_tblAlias != value)
                {
                    _tblAlias = value;
                    OnPropertyChanged("tblAlias");
                }
            }
        }
        private string _tblAlias;
    
        [DataMember]
        public string tblName
        {
            get { return _tblName; }
            set
            {
                if (_tblName != value)
                {
                    _tblName = value;
                    OnPropertyChanged("tblName");
                }
            }
        }
        private string _tblName;
    
        [DataMember]
        public string selectType
        {
            get { return _selectType; }
            set
            {
                if (_selectType != value)
                {
                    _selectType = value;
                    OnPropertyChanged("selectType");
                }
            }
        }
        private string _selectType;
    
        [DataMember]
        public string selectWhat
        {
            get { return _selectWhat; }
            set
            {
                if (_selectWhat != value)
                {
                    _selectWhat = value;
                    OnPropertyChanged("selectWhat");
                }
            }
        }
        private string _selectWhat;
    
        [DataMember]
        public string whereClause
        {
            get { return _whereClause; }
            set
            {
                if (_whereClause != value)
                {
                    _whereClause = value;
                    OnPropertyChanged("whereClause");
                }
            }
        }
        private string _whereClause;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
